#  Генерит Terraform
#  ВМ адресуются по FQDN .ru-central1.internal, без IP.

[bastion]
localhost ansible_connection=local

[web]
web-a.ru-central1.internal
web-b.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[elastic]
elastic.ru-central1.internal

[kibana]
kibana.ru-central1.internal

[monitored:children]
bastion
web
zabbix
elastic
kibana
